import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { saveAs } from 'file-saver';
import JSZip from 'jszip';

export interface MeasurementExportData {
  projectName?: string;
  projectCode?: string;
  drawingTitle?: string;
  scaleInfo?: string;
  measurements: Array<{
    id: string;
    type: string;
    label: string | null;
    value: number;
    unit: string;
    color: string;
    notes: string | null;
    created_at: string;
    created_by?: string;
  }>;
  metadata?: Record<string, any>;
  generatedAt: string;
  generatedBy?: string;
}

export interface ExportOptions {
  format: 'csv' | 'pdf' | 'xlsx' | 'json' | 'xml';
  includeMetadata?: boolean;
  includeCalibration?: boolean;
  pdfOrientation?: 'portrait' | 'landscape';
  csvDelimiter?: ',' | ';' | '\t';
  fileName?: string;
  compress?: boolean;
}

function formatValue(val: number, unit: string): string {
  if (unit === 'm²' || unit === 'ft²') return val.toFixed(2) + ' ' + unit;
  return val.toFixed(3) + ' ' + unit;
}

// ─── CSV ───
export function exportCSV(data: MeasurementExportData, opts: ExportOptions): string {
  const d = opts.csvDelimiter || ',';
  const esc = (s: string) => `"${(s || '').replace(/"/g, '""')}"`;
  
  let csv = '';
  if (opts.includeMetadata) {
    csv += `Project${d}${esc(data.projectName || '')}${d}Code${d}${esc(data.projectCode || '')}\n`;
    csv += `Drawing${d}${esc(data.drawingTitle || '')}${d}Scale${d}${esc(data.scaleInfo || '')}\n`;
    csv += `Generated${d}${esc(data.generatedAt)}${d}By${d}${esc(data.generatedBy || '')}\n\n`;
  }
  
  csv += ['#', 'Type', 'Label', 'Value', 'Unit', 'Notes', 'Date'].map(esc).join(d) + '\n';
  data.measurements.forEach((m, i) => {
    csv += [i + 1, m.type, m.label || '', m.value.toFixed(3), m.unit, m.notes || '', m.created_at.split('T')[0]].map(String).map(esc).join(d) + '\n';
  });
  
  return csv;
}

// ─── PDF ───
export function exportPDF(data: MeasurementExportData, opts: ExportOptions): jsPDF {
  const doc = new jsPDF({ orientation: opts.pdfOrientation || 'portrait', unit: 'mm', format: 'a4' });
  const w = doc.internal.pageSize.getWidth();
  
  // Header
  doc.setFillColor(26, 86, 219);
  doc.rect(0, 0, w, 28, 'F');
  doc.setTextColor(255);
  doc.setFontSize(16);
  doc.text('Measurement Report', 14, 12);
  doc.setFontSize(9);
  doc.text(data.projectName || 'Untitled Project', 14, 19);
  doc.text(data.generatedAt.split('T')[0], w - 14, 12, { align: 'right' });
  doc.text(`Generated by: ${data.generatedBy || 'System'}`, w - 14, 19, { align: 'right' });
  
  // Project Info
  doc.setTextColor(0);
  let y = 36;
  doc.setFontSize(10);
  if (data.projectCode) { doc.text(`Project Code: ${data.projectCode}`, 14, y); y += 6; }
  if (data.drawingTitle) { doc.text(`Drawing: ${data.drawingTitle}`, 14, y); y += 6; }
  if (data.scaleInfo) { doc.text(`Scale: ${data.scaleInfo}`, 14, y); y += 6; }
  
  // Summary stats
  y += 4;
  const vals = data.measurements.map(m => m.value);
  const sum = vals.reduce((a, b) => a + b, 0);
  const avg = vals.length ? sum / vals.length : 0;
  doc.setFontSize(9);
  doc.setFont(undefined as any, 'bold');
  doc.text('Summary Statistics', 14, y); y += 5;
  doc.setFont(undefined as any, 'normal');
  doc.text(`Total: ${data.measurements.length} measurements  |  Sum: ${sum.toFixed(2)}  |  Avg: ${avg.toFixed(2)}  |  Min: ${Math.min(...vals).toFixed(2)}  |  Max: ${Math.max(...vals).toFixed(2)}`, 14, y);
  y += 8;
  
  // Table
  autoTable(doc, {
    startY: y,
    head: [['#', 'Type', 'Label', 'Value', 'Unit', 'Notes']],
    body: data.measurements.map((m, i) => [
      i + 1,
      m.type.charAt(0).toUpperCase() + m.type.slice(1),
      m.label || '-',
      m.value.toFixed(3),
      m.unit,
      m.notes || '-',
    ]),
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [26, 86, 219], textColor: 255 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    margin: { left: 14, right: 14 },
  });
  
  // Footer
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    const h = doc.internal.pageSize.getHeight();
    doc.setFontSize(7);
    doc.setTextColor(128);
    doc.text(`Page ${i} of ${pages}`, w / 2, h - 8, { align: 'center' });
    doc.text('CPMS Measurement Report — Confidential', 14, h - 8);
  }
  
  return doc;
}

// ─── XLSX ───
export function exportXLSX(data: MeasurementExportData, opts: ExportOptions): XLSX.WorkBook {
  const wb = XLSX.utils.book_new();
  
  // Summary sheet
  const summaryData = [
    ['Measurement Report'],
    [],
    ['Project', data.projectName || ''],
    ['Code', data.projectCode || ''],
    ['Drawing', data.drawingTitle || ''],
    ['Scale', data.scaleInfo || ''],
    ['Generated', data.generatedAt],
    ['By', data.generatedBy || ''],
    [],
    ['Statistics'],
    ['Total Measurements', data.measurements.length],
    ['Sum', data.measurements.reduce((a, m) => a + m.value, 0)],
    ['Average', data.measurements.length ? data.measurements.reduce((a, m) => a + m.value, 0) / data.measurements.length : 0],
    ['Min', Math.min(...data.measurements.map(m => m.value))],
    ['Max', Math.max(...data.measurements.map(m => m.value))],
  ];
  const ws1 = XLSX.utils.aoa_to_sheet(summaryData);
  XLSX.utils.book_append_sheet(wb, ws1, 'Summary');
  
  // Measurements sheet
  const measData = [
    ['#', 'Type', 'Label', 'Value', 'Unit', 'Color', 'Notes', 'Date'],
    ...data.measurements.map((m, i) => [
      i + 1, m.type, m.label || '', m.value, m.unit, m.color, m.notes || '', m.created_at.split('T')[0],
    ]),
  ];
  const ws2 = XLSX.utils.aoa_to_sheet(measData);
  ws2['!cols'] = [{ wch: 5 }, { wch: 12 }, { wch: 20 }, { wch: 12 }, { wch: 8 }, { wch: 10 }, { wch: 30 }, { wch: 12 }];
  XLSX.utils.book_append_sheet(wb, ws2, 'Measurements');
  
  // By Type sheet
  const types = [...new Set(data.measurements.map(m => m.type))];
  const byTypeData = [
    ['Type', 'Count', 'Sum', 'Average', 'Min', 'Max'],
    ...types.map(t => {
      const items = data.measurements.filter(m => m.type === t);
      const vals = items.map(m => m.value);
      return [t, items.length, vals.reduce((a, b) => a + b, 0), vals.reduce((a, b) => a + b, 0) / vals.length, Math.min(...vals), Math.max(...vals)];
    }),
  ];
  const ws3 = XLSX.utils.aoa_to_sheet(byTypeData);
  XLSX.utils.book_append_sheet(wb, ws3, 'By Type');
  
  return wb;
}

// ─── JSON ───
export function exportJSON(data: MeasurementExportData): string {
  return JSON.stringify({
    report: {
      project: { name: data.projectName, code: data.projectCode },
      drawing: { title: data.drawingTitle, scale: data.scaleInfo },
      generated: { at: data.generatedAt, by: data.generatedBy },
    },
    statistics: {
      count: data.measurements.length,
      sum: data.measurements.reduce((a, m) => a + m.value, 0),
      average: data.measurements.length ? data.measurements.reduce((a, m) => a + m.value, 0) / data.measurements.length : 0,
    },
    measurements: data.measurements.map((m, i) => ({
      index: i + 1,
      type: m.type,
      label: m.label,
      value: m.value,
      unit: m.unit,
      notes: m.notes,
      date: m.created_at,
    })),
    metadata: data.metadata,
  }, null, 2);
}

// ─── XML ───
export function exportXML(data: MeasurementExportData): string {
  const esc = (s: string) => (s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  let xml = '<?xml version="1.0" encoding="UTF-8"?>\n<MeasurementReport>\n';
  xml += `  <Project name="${esc(data.projectName || '')}" code="${esc(data.projectCode || '')}" />\n`;
  xml += `  <Drawing title="${esc(data.drawingTitle || '')}" scale="${esc(data.scaleInfo || '')}" />\n`;
  xml += `  <Generated at="${esc(data.generatedAt)}" by="${esc(data.generatedBy || '')}" />\n`;
  xml += '  <Measurements>\n';
  data.measurements.forEach((m, i) => {
    xml += `    <Measurement index="${i + 1}" type="${esc(m.type)}" label="${esc(m.label || '')}" value="${m.value}" unit="${esc(m.unit)}" date="${m.created_at.split('T')[0]}"`;
    if (m.notes) xml += ` notes="${esc(m.notes)}"`;
    xml += ' />\n';
  });
  xml += '  </Measurements>\n</MeasurementReport>';
  return xml;
}

// ─── Main Export ───
export async function performExport(data: MeasurementExportData, opts: ExportOptions): Promise<{ blob: Blob; fileName: string; size: number }> {
  const baseName = opts.fileName || `measurement-report-${Date.now()}`;
  let blob: Blob;
  let fileName: string;
  
  const start = Date.now();

  switch (opts.format) {
    case 'csv': {
      const csv = exportCSV(data, opts);
      blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
      fileName = `${baseName}.csv`;
      break;
    }
    case 'pdf': {
      const doc = exportPDF(data, opts);
      blob = doc.output('blob');
      fileName = `${baseName}.pdf`;
      break;
    }
    case 'xlsx': {
      const wb = exportXLSX(data, opts);
      const buf = XLSX.write(wb, { type: 'array', bookType: 'xlsx' });
      blob = new Blob([buf], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
      fileName = `${baseName}.xlsx`;
      break;
    }
    case 'json': {
      const json = exportJSON(data);
      blob = new Blob([json], { type: 'application/json' });
      fileName = `${baseName}.json`;
      break;
    }
    case 'xml': {
      const xml = exportXML(data);
      blob = new Blob([xml], { type: 'application/xml' });
      fileName = `${baseName}.xml`;
      break;
    }
    default:
      throw new Error(`Unsupported format: ${opts.format}`);
  }

  if (opts.compress) {
    const zip = new JSZip();
    zip.file(fileName, blob);
    blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE', compressionOptions: { level: 6 } });
    fileName = `${baseName}.zip`;
  }

  return { blob, fileName, size: blob.size };
}

export function downloadBlob(blob: Blob, fileName: string) {
  saveAs(blob, fileName);
}

export function formatFileSize(bytes: number): string {
  if (bytes < 1024) return bytes + ' B';
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
  return (bytes / (1024 * 1024)).toFixed(2) + ' MB';
}
