import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, serviceRoleKey);

    // Get active follow-up rules
    const { data: rules, error: rulesError } = await supabase
      .from("follow_up_rules")
      .select("*")
      .eq("is_active", true);

    if (rulesError) throw rulesError;
    if (!rules?.length) {
      return new Response(JSON.stringify({ message: "No active rules", processed: 0 }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const now = new Date();
    let totalActions = 0;
    const results: any[] = [];

    for (const rule of rules) {
      try {
        const config = rule.action_config || {};

        if (rule.trigger_type === "no_activity" && rule.entity_type === "lead") {
          // Find leads with no recent activity
          const cutoffDate = new Date(now.getTime() - rule.trigger_days * 24 * 60 * 60 * 1000).toISOString();

          const { data: leads } = await supabase
            .from("business_partners")
            .select("id, card_name, assigned_to")
            .eq("card_type", "lead")
            .eq("status", "active");

          if (!leads?.length) continue;

          for (const lead of leads) {
            // Check if there's recent activity for this lead
            const { count: recentCount } = await supabase
              .from("activities")
              .select("id", { count: "exact", head: true })
              .eq("business_partner_id", lead.id)
              .gte("created_at", cutoffDate);

            if ((recentCount || 0) > 0) continue;

            // Check if we already created a follow-up recently (avoid duplicates)
            const { count: existingLog } = await supabase
              .from("follow_up_logs")
              .select("id", { count: "exact", head: true })
              .eq("rule_id", rule.id)
              .eq("business_partner_id", lead.id)
              .gte("created_at", cutoffDate);

            if ((existingLog || 0) > 0) continue;

            if (rule.action_type === "create_task") {
              const subject = (config.subject_template || "Follow up with {name}")
                .replace("{name}", lead.card_name)
                .replace("{days}", String(rule.trigger_days));

              const { data: activity, error: actError } = await supabase
                .from("activities")
                .insert({
                  subject,
                  type: config.type || "task",
                  status: "pending",
                  priority: config.priority || "medium",
                  business_partner_id: lead.id,
                  assigned_to: lead.assigned_to,
                  due_date: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString(),
                  description: `Auto-generated by rule: ${rule.name}`,
                })
                .select("id")
                .single();

              if (!actError && activity) {
                await supabase.from("follow_up_logs").insert({
                  rule_id: rule.id,
                  business_partner_id: lead.id,
                  activity_id: activity.id,
                  action_taken: "create_task",
                  details: subject,
                });
                totalActions++;
              }
            } else if (rule.action_type === "create_notification" && lead.assigned_to) {
              const message = (config.subject_template || "Follow up needed for {name}")
                .replace("{name}", lead.card_name);

              await supabase.from("workflow_notifications").insert({
                user_id: lead.assigned_to,
                title: `Follow-up Reminder: ${lead.card_name}`,
                message,
                notification_type: "reminder",
                link_url: "/leads",
              });

              await supabase.from("follow_up_logs").insert({
                rule_id: rule.id,
                business_partner_id: lead.id,
                action_taken: "create_notification",
                details: message,
              });
              totalActions++;
            }
          }
        }

        if (rule.trigger_type === "no_activity" && rule.entity_type === "opportunity") {
          const cutoffDate = new Date(now.getTime() - rule.trigger_days * 24 * 60 * 60 * 1000).toISOString();

          const { data: opps } = await supabase
            .from("opportunities")
            .select("id, title, owner_id, business_partner_id")
            .not("stage", "in", '("Closed Won","Closed Lost")');

          if (!opps?.length) continue;

          for (const opp of opps) {
            const { count: recentCount } = await supabase
              .from("activities")
              .select("id", { count: "exact", head: true })
              .eq("opportunity_id", opp.id)
              .gte("created_at", cutoffDate);

            if ((recentCount || 0) > 0) continue;

            const { count: existingLog } = await supabase
              .from("follow_up_logs")
              .select("id", { count: "exact", head: true })
              .eq("rule_id", rule.id)
              .eq("business_partner_id", opp.business_partner_id)
              .gte("created_at", cutoffDate);

            if ((existingLog || 0) > 0) continue;

            const subject = (config.subject_template || "Review opportunity: {name}")
              .replace("{name}", opp.title || "Untitled");

            const { data: activity } = await supabase
              .from("activities")
              .insert({
                subject,
                type: config.type || "task",
                status: "pending",
                priority: config.priority || "high",
                opportunity_id: opp.id,
                business_partner_id: opp.business_partner_id,
                assigned_to: opp.owner_id,
                due_date: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString(),
                description: `Auto-generated by rule: ${rule.name}`,
              })
              .select("id")
              .single();

            if (activity) {
              await supabase.from("follow_up_logs").insert({
                rule_id: rule.id,
                business_partner_id: opp.business_partner_id,
                activity_id: activity.id,
                action_taken: "create_task",
                details: subject,
              });
              totalActions++;
            }
          }
        }

        if (rule.trigger_type === "overdue_activity") {
          const cutoffDate = new Date(now.getTime() - rule.trigger_days * 24 * 60 * 60 * 1000).toISOString();

          const { data: overdueActivities } = await supabase
            .from("activities")
            .select("id, subject, assigned_to, business_partner_id")
            .eq("status", "pending")
            .lt("due_date", cutoffDate);

          if (!overdueActivities?.length) continue;

          for (const act of overdueActivities) {
            if (!act.assigned_to) continue;

            const { count: existingLog } = await supabase
              .from("follow_up_logs")
              .select("id", { count: "exact", head: true })
              .eq("rule_id", rule.id)
              .eq("activity_id", act.id)
              .gte("created_at", new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString());

            if ((existingLog || 0) > 0) continue;

            await supabase.from("workflow_notifications").insert({
              user_id: act.assigned_to,
              title: `Overdue Activity Escalation`,
              message: `Activity "${act.subject}" is overdue by more than ${rule.trigger_days} days. Please take action.`,
              notification_type: "reminder",
              link_url: "/activities",
            });

            await supabase.from("follow_up_logs").insert({
              rule_id: rule.id,
              business_partner_id: act.business_partner_id,
              activity_id: act.id,
              action_taken: "escalation_notification",
              details: `Escalated overdue activity: ${act.subject}`,
            });
            totalActions++;
          }
        }

        results.push({ rule: rule.name, status: "processed" });
      } catch (ruleErr) {
        console.error(`Error processing rule ${rule.name}:`, ruleErr);
        results.push({ rule: rule.name, status: "error", error: String(ruleErr) });
      }
    }

    return new Response(JSON.stringify({ processed: totalActions, rules: results }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("Follow-up automation error:", error);
    return new Response(JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
