/**
 * Data Transfer Workbench - Entity Registry
 * Defines all importable/exportable entities grouped by module
 */

export interface DTWColumn {
  key: string;
  header: string;
  required?: boolean;
  type?: 'text' | 'number' | 'date' | 'boolean' | 'enum';
  enumValues?: string[];
  description?: string;
  foreignTable?: string;
  foreignKey?: string;
}

export interface DTWEntity {
  id: string;
  table: string;
  label: string;
  labelAr: string;
  description: string;
  descriptionAr: string;
  keyField: string; // field used for upsert matching
  columns: DTWColumn[];
}

export interface DTWModule {
  id: string;
  label: string;
  labelAr: string;
  icon: string;
  entities: DTWEntity[];
}

export const dtwModules: DTWModule[] = [
  {
    id: 'finance',
    label: 'Finance',
    labelAr: 'المالية',
    icon: 'DollarSign',
    entities: [
      {
        id: 'chart_of_accounts',
        table: 'chart_of_accounts',
        label: 'Chart of Accounts',
        labelAr: 'دليل الحسابات',
        description: 'GL accounts master data',
        descriptionAr: 'بيانات الحسابات الرئيسية',
        keyField: 'account_code',
        columns: [
          { key: 'account_code', header: 'Account Code', required: true },
          { key: 'account_name', header: 'Account Name', required: true },
          { key: 'account_type', header: 'Account Type', required: true, type: 'enum', enumValues: ['asset', 'liability', 'equity', 'revenue', 'expense'] },
          { key: 'parent_code', header: 'Parent Code' },
          { key: 'currency', header: 'Currency' },
          { key: 'is_active', header: 'Active', type: 'boolean' },
          { key: 'level', header: 'Level', type: 'number' },
        ],
      },
      {
        id: 'journal_entries',
        table: 'journal_entries',
        label: 'Journal Entries',
        labelAr: 'القيود اليومية',
        description: 'General ledger journal entries',
        descriptionAr: 'قيود دفتر الأستاذ العام',
        keyField: 'doc_number',
        columns: [
          { key: 'doc_number', header: 'Doc Number', required: true },
          { key: 'posting_date', header: 'Posting Date', required: true, type: 'date' },
          { key: 'due_date', header: 'Due Date', type: 'date' },
          { key: 'reference', header: 'Reference' },
          { key: 'memo', header: 'Memo' },
          { key: 'status', header: 'Status', type: 'enum', enumValues: ['draft', 'posted', 'cancelled'] },
          { key: 'total_debit', header: 'Total Debit', type: 'number' },
          { key: 'total_credit', header: 'Total Credit', type: 'number' },
        ],
      },
      {
        id: 'dimensions',
        table: 'dimensions',
        label: 'Dimensions',
        labelAr: 'الأبعاد',
        description: 'Cost centers / dimensions master data',
        descriptionAr: 'بيانات مراكز التكلفة',
        keyField: 'cost_center',
        columns: [
          { key: 'dimension_type', header: 'Type', required: true, type: 'enum', enumValues: ['employees', 'branches', 'business_line', 'factory'] },
          { key: 'cost_center', header: 'Cost Center', required: true },
          { key: 'name', header: 'Name', required: true },
          { key: 'dimension_code', header: 'Code' },
          { key: 'effective_from', header: 'Effective From', type: 'date' },
          { key: 'effective_to', header: 'Effective To', type: 'date' },
          { key: 'is_active', header: 'Active', type: 'boolean' },
        ],
      },
      {
        id: 'tax_codes',
        table: 'tax_codes',
        label: 'Tax Codes',
        labelAr: 'أكواد الضريبة',
        description: 'Tax codes configuration',
        descriptionAr: 'إعداد أكواد الضريبة',
        keyField: 'code',
        columns: [
          { key: 'code', header: 'Code', required: true },
          { key: 'name', header: 'Name', required: true },
          { key: 'rate', header: 'Rate (%)', required: true, type: 'number' },
          { key: 'is_active', header: 'Active', type: 'boolean' },
        ],
      },
    ],
  },
  {
    id: 'sales',
    label: 'Sales',
    labelAr: 'المبيعات',
    icon: 'TrendingUp',
    entities: [
      {
        id: 'business_partners',
        table: 'business_partners',
        label: 'Business Partners',
        labelAr: 'شركاء الأعمال',
        description: 'Customers and vendors',
        descriptionAr: 'العملاء والموردين',
        keyField: 'card_code',
        columns: [
          { key: 'card_code', header: 'Card Code', required: true },
          { key: 'card_name', header: 'Card Name', required: true },
          { key: 'card_type', header: 'Type', required: true, type: 'enum', enumValues: ['customer', 'vendor', 'lead'] },
          { key: 'contact_person', header: 'Contact Person' },
          { key: 'phone', header: 'Phone' },
          { key: 'email', header: 'Email' },
          { key: 'address', header: 'Address' },
          { key: 'city', header: 'City' },
          { key: 'country', header: 'Country' },
          { key: 'currency', header: 'Currency' },
          { key: 'credit_limit', header: 'Credit Limit', type: 'number' },
          { key: 'payment_terms', header: 'Payment Terms' },
          { key: 'tax_id', header: 'Tax ID' },
          { key: 'is_active', header: 'Active', type: 'boolean' },
        ],
      },
      {
        id: 'sales_orders',
        table: 'sales_orders',
        label: 'Sales Orders',
        labelAr: 'أوامر البيع',
        description: 'Sales order transactions',
        descriptionAr: 'معاملات أوامر البيع',
        keyField: 'order_number',
        columns: [
          { key: 'order_number', header: 'Order Number', required: true },
          { key: 'customer_code', header: 'Customer Code', required: true },
          { key: 'customer_name', header: 'Customer Name', required: true },
          { key: 'doc_date', header: 'Doc Date', required: true, type: 'date' },
          { key: 'delivery_date', header: 'Delivery Date', type: 'date' },
          { key: 'status', header: 'Status', type: 'enum', enumValues: ['draft', 'open', 'closed', 'cancelled'] },
          { key: 'total', header: 'Total', type: 'number' },
          { key: 'currency', header: 'Currency' },
          { key: 'remarks', header: 'Remarks' },
        ],
      },
      {
        id: 'ar_invoices',
        table: 'ar_invoices',
        label: 'AR Invoices',
        labelAr: 'فواتير المبيعات',
        description: 'Accounts receivable invoices',
        descriptionAr: 'فواتير الحسابات المدينة',
        keyField: 'doc_num',
        columns: [
          { key: 'doc_num', header: 'Doc Number', required: true, type: 'number' },
          { key: 'customer_code', header: 'Customer Code', required: true },
          { key: 'customer_name', header: 'Customer Name', required: true },
          { key: 'doc_date', header: 'Doc Date', required: true, type: 'date' },
          { key: 'doc_due_date', header: 'Due Date', type: 'date' },
          { key: 'status', header: 'Status' },
          { key: 'subtotal', header: 'Subtotal', type: 'number' },
          { key: 'tax_amount', header: 'Tax Amount', type: 'number' },
          { key: 'total', header: 'Total', type: 'number' },
          { key: 'currency', header: 'Currency' },
          { key: 'remarks', header: 'Remarks' },
        ],
      },
      {
        id: 'ar_credit_memos',
        table: 'ar_credit_memos',
        label: 'AR Credit Memos',
        labelAr: 'إشعارات دائنة مبيعات',
        description: 'Sales credit memos',
        descriptionAr: 'إشعارات الدائنة للمبيعات',
        keyField: 'doc_num',
        columns: [
          { key: 'doc_num', header: 'Doc Number', required: true, type: 'number' },
          { key: 'customer_code', header: 'Customer Code', required: true },
          { key: 'customer_name', header: 'Customer Name', required: true },
          { key: 'doc_date', header: 'Doc Date', required: true, type: 'date' },
          { key: 'reference_invoice', header: 'Reference Invoice' },
          { key: 'total', header: 'Total', type: 'number' },
          { key: 'status', header: 'Status' },
          { key: 'remarks', header: 'Remarks' },
        ],
      },
      {
        id: 'leads',
        table: 'leads',
        label: 'Leads',
        labelAr: 'العملاء المحتملين',
        description: 'Sales leads',
        descriptionAr: 'العملاء المحتملين',
        keyField: 'name',
        columns: [
          { key: 'name', header: 'Name', required: true },
          { key: 'company', header: 'Company' },
          { key: 'email', header: 'Email' },
          { key: 'phone', header: 'Phone' },
          { key: 'source', header: 'Source' },
          { key: 'status', header: 'Status', type: 'enum', enumValues: ['new', 'contacted', 'qualified', 'converted', 'lost'] },
          { key: 'value', header: 'Value', type: 'number' },
        ],
      },
      {
        id: 'opportunities',
        table: 'opportunities',
        label: 'Opportunities',
        labelAr: 'الفرص',
        description: 'Sales opportunities',
        descriptionAr: 'فرص المبيعات',
        keyField: 'name',
        columns: [
          { key: 'name', header: 'Name', required: true },
          { key: 'business_partner_id', header: 'BP ID' },
          { key: 'stage', header: 'Stage' },
          { key: 'amount', header: 'Amount', type: 'number' },
          { key: 'close_date', header: 'Close Date', type: 'date' },
          { key: 'probability', header: 'Probability (%)', type: 'number' },
          { key: 'status', header: 'Status' },
        ],
      },
      {
        id: 'sales_employees',
        table: 'sales_employees',
        label: 'Sales Employees',
        labelAr: 'موظفي المبيعات',
        description: 'Sales representatives',
        descriptionAr: 'ممثلي المبيعات',
        keyField: 'employee_code',
        columns: [
          { key: 'employee_code', header: 'Employee Code', required: true, type: 'number' },
          { key: 'employee_name', header: 'Employee Name', required: true },
          { key: 'department', header: 'Department' },
          { key: 'position', header: 'Position' },
          { key: 'phone', header: 'Phone' },
          { key: 'email', header: 'Email' },
          { key: 'is_active', header: 'Active', type: 'boolean' },
        ],
      },
    ],
  },
  {
    id: 'procurement',
    label: 'Procurement',
    labelAr: 'المشتريات',
    icon: 'ShoppingCart',
    entities: [
      {
        id: 'purchase_orders',
        table: 'purchase_orders',
        label: 'Purchase Orders',
        labelAr: 'أوامر الشراء',
        description: 'Purchase order transactions',
        descriptionAr: 'معاملات أوامر الشراء',
        keyField: 'order_number',
        columns: [
          { key: 'order_number', header: 'Order Number', required: true },
          { key: 'vendor_code', header: 'Vendor Code', required: true },
          { key: 'vendor_name', header: 'Vendor Name', required: true },
          { key: 'doc_date', header: 'Doc Date', required: true, type: 'date' },
          { key: 'delivery_date', header: 'Delivery Date', type: 'date' },
          { key: 'status', header: 'Status' },
          { key: 'total', header: 'Total', type: 'number' },
          { key: 'currency', header: 'Currency' },
          { key: 'remarks', header: 'Remarks' },
        ],
      },
      {
        id: 'ap_invoices',
        table: 'ap_invoices',
        label: 'AP Invoices',
        labelAr: 'فواتير المشتريات',
        description: 'Accounts payable invoices',
        descriptionAr: 'فواتير الحسابات الدائنة',
        keyField: 'invoice_number',
        columns: [
          { key: 'invoice_number', header: 'Invoice Number', required: true },
          { key: 'vendor_name', header: 'Vendor Name', required: true },
          { key: 'vendor_code', header: 'Vendor Code' },
          { key: 'doc_date', header: 'Doc Date', required: true, type: 'date' },
          { key: 'doc_due_date', header: 'Due Date', type: 'date' },
          { key: 'status', header: 'Status' },
          { key: 'subtotal', header: 'Subtotal', type: 'number' },
          { key: 'tax_amount', header: 'Tax Amount', type: 'number' },
          { key: 'total', header: 'Total', type: 'number' },
          { key: 'remarks', header: 'Remarks' },
        ],
      },
      {
        id: 'ap_credit_memos',
        table: 'ap_credit_memos',
        label: 'AP Credit Memos',
        labelAr: 'إشعارات دائنة مشتريات',
        description: 'Purchase credit memos',
        descriptionAr: 'إشعارات دائنة المشتريات',
        keyField: 'doc_num',
        columns: [
          { key: 'doc_num', header: 'Doc Number', required: true, type: 'number' },
          { key: 'vendor_code', header: 'Vendor Code', required: true },
          { key: 'vendor_name', header: 'Vendor Name', required: true },
          { key: 'doc_date', header: 'Doc Date', required: true, type: 'date' },
          { key: 'reference_invoice', header: 'Reference Invoice' },
          { key: 'total', header: 'Total', type: 'number' },
          { key: 'status', header: 'Status' },
          { key: 'remarks', header: 'Remarks' },
        ],
      },
      {
        id: 'goods_receipts',
        table: 'goods_receipts',
        label: 'Goods Receipts',
        labelAr: 'استلام البضائع',
        description: 'Goods receipt PO transactions',
        descriptionAr: 'معاملات استلام البضائع',
        keyField: 'doc_number',
        columns: [
          { key: 'doc_number', header: 'Doc Number', required: true },
          { key: 'vendor_code', header: 'Vendor Code' },
          { key: 'vendor_name', header: 'Vendor Name' },
          { key: 'doc_date', header: 'Doc Date', required: true, type: 'date' },
          { key: 'status', header: 'Status' },
          { key: 'total', header: 'Total', type: 'number' },
          { key: 'remarks', header: 'Remarks' },
        ],
      },
    ],
  },
  {
    id: 'inventory',
    label: 'Inventory',
    labelAr: 'المخزون',
    icon: 'Package',
    entities: [
      {
        id: 'items',
        table: 'items',
        label: 'Items',
        labelAr: 'الأصناف',
        description: 'Item master data',
        descriptionAr: 'بيانات الأصناف الرئيسية',
        keyField: 'item_code',
        columns: [
          { key: 'item_code', header: 'Item Code', required: true },
          { key: 'item_name', header: 'Item Name', required: true },
          { key: 'item_type', header: 'Type', type: 'enum', enumValues: ['item', 'service', 'fixed_asset'] },
          { key: 'item_group', header: 'Group' },
          { key: 'uom', header: 'UoM' },
          { key: 'price', header: 'Price', type: 'number' },
          { key: 'cost', header: 'Cost', type: 'number' },
          { key: 'barcode', header: 'Barcode' },
          { key: 'is_active', header: 'Active', type: 'boolean' },
          { key: 'warehouse', header: 'Default Warehouse' },
          { key: 'min_stock', header: 'Min Stock', type: 'number' },
          { key: 'max_stock', header: 'Max Stock', type: 'number' },
        ],
      },
      {
        id: 'warehouses',
        table: 'warehouses',
        label: 'Warehouses',
        labelAr: 'المستودعات',
        description: 'Warehouse master data',
        descriptionAr: 'بيانات المستودعات',
        keyField: 'warehouse_code',
        columns: [
          { key: 'warehouse_code', header: 'Code', required: true },
          { key: 'warehouse_name', header: 'Name', required: true },
          { key: 'location', header: 'Location' },
          { key: 'is_active', header: 'Active', type: 'boolean' },
        ],
      },
      {
        id: 'price_lists',
        table: 'price_lists',
        label: 'Price Lists',
        labelAr: 'قوائم الأسعار',
        description: 'Price list master data',
        descriptionAr: 'بيانات قوائم الأسعار',
        keyField: 'name',
        columns: [
          { key: 'name', header: 'Name', required: true },
          { key: 'currency', header: 'Currency' },
          { key: 'is_active', header: 'Active', type: 'boolean' },
        ],
      },
    ],
  },
  {
    id: 'hr',
    label: 'Human Resources',
    labelAr: 'الموارد البشرية',
    icon: 'Users',
    entities: [
      {
        id: 'employees',
        table: 'employees',
        label: 'Employees',
        labelAr: 'الموظفين',
        description: 'Employee master data',
        descriptionAr: 'بيانات الموظفين',
        keyField: 'employee_code',
        columns: [
          { key: 'employee_code', header: 'Employee Code', required: true },
          { key: 'first_name', header: 'First Name', required: true },
          { key: 'last_name', header: 'Last Name', required: true },
          { key: 'department', header: 'Department' },
          { key: 'position', header: 'Position' },
          { key: 'hire_date', header: 'Hire Date', type: 'date' },
          { key: 'email', header: 'Email' },
          { key: 'phone', header: 'Phone' },
          { key: 'status', header: 'Status', type: 'enum', enumValues: ['active', 'inactive', 'terminated'] },
          { key: 'nationality', header: 'Nationality' },
          { key: 'id_number', header: 'ID Number' },
        ],
      },
      {
        id: 'departments',
        table: 'departments',
        label: 'Departments',
        labelAr: 'الأقسام',
        description: 'Department master data',
        descriptionAr: 'بيانات الأقسام',
        keyField: 'name',
        columns: [
          { key: 'name', header: 'Name', required: true },
          { key: 'code', header: 'Code' },
          { key: 'parent_department', header: 'Parent Department' },
          { key: 'manager', header: 'Manager' },
          { key: 'is_active', header: 'Active', type: 'boolean' },
        ],
      },
      {
        id: 'positions',
        table: 'positions',
        label: 'Positions',
        labelAr: 'المناصب',
        description: 'Job positions',
        descriptionAr: 'المناصب الوظيفية',
        keyField: 'title',
        columns: [
          { key: 'title', header: 'Title', required: true },
          { key: 'department', header: 'Department' },
          { key: 'level', header: 'Level' },
          { key: 'is_active', header: 'Active', type: 'boolean' },
        ],
      },
    ],
  },
  {
    id: 'projects',
    label: 'Projects',
    labelAr: 'المشاريع',
    icon: 'FolderKanban',
    entities: [
      {
        id: 'projects',
        table: 'projects',
        label: 'Projects',
        labelAr: 'المشاريع',
        description: 'Project master data',
        descriptionAr: 'بيانات المشاريع',
        keyField: 'project_code',
        columns: [
          { key: 'project_code', header: 'Project Code', required: true },
          { key: 'project_name', header: 'Project Name', required: true },
          { key: 'customer_code', header: 'Customer Code' },
          { key: 'customer_name', header: 'Customer Name' },
          { key: 'start_date', header: 'Start Date', type: 'date' },
          { key: 'end_date', header: 'End Date', type: 'date' },
          { key: 'status', header: 'Status', type: 'enum', enumValues: ['planning', 'active', 'on_hold', 'completed', 'cancelled'] },
          { key: 'budget', header: 'Budget', type: 'number' },
          { key: 'manager', header: 'Project Manager' },
        ],
      },
    ],
  },
  {
    id: 'fixed_assets',
    label: 'Fixed Assets',
    labelAr: 'الأصول الثابتة',
    icon: 'HardDrive',
    entities: [
      {
        id: 'fixed_assets',
        table: 'fixed_assets',
        label: 'Fixed Assets',
        labelAr: 'الأصول الثابتة',
        description: 'Fixed assets register',
        descriptionAr: 'سجل الأصول الثابتة',
        keyField: 'asset_code',
        columns: [
          { key: 'asset_code', header: 'Asset Code', required: true },
          { key: 'asset_name', header: 'Asset Name', required: true },
          { key: 'category', header: 'Category' },
          { key: 'acquisition_date', header: 'Acquisition Date', type: 'date' },
          { key: 'acquisition_cost', header: 'Acquisition Cost', type: 'number' },
          { key: 'depreciation_method', header: 'Depreciation Method' },
          { key: 'useful_life', header: 'Useful Life (Years)', type: 'number' },
          { key: 'location', header: 'Location' },
          { key: 'status', header: 'Status', type: 'enum', enumValues: ['active', 'disposed', 'under_maintenance'] },
        ],
      },
    ],
  },
  {
    id: 'activities',
    label: 'Activities & Tasks',
    labelAr: 'الأنشطة والمهام',
    icon: 'Activity',
    entities: [
      {
        id: 'activities',
        table: 'activities',
        label: 'Activities',
        labelAr: 'الأنشطة',
        description: 'CRM activities (calls, meetings, tasks)',
        descriptionAr: 'أنشطة إدارة العلاقات',
        keyField: 'subject',
        columns: [
          { key: 'subject', header: 'Subject', required: true },
          { key: 'type', header: 'Type', required: true, type: 'enum', enumValues: ['call', 'meeting', 'task', 'email', 'note', 'other'] },
          { key: 'status', header: 'Status' },
          { key: 'priority', header: 'Priority', type: 'enum', enumValues: ['low', 'medium', 'high'] },
          { key: 'due_date', header: 'Due Date', type: 'date' },
          { key: 'description', header: 'Description' },
          { key: 'card_code', header: 'BP Card Code' },
          { key: 'location', header: 'Location' },
        ],
      },
    ],
  },
];
