import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, serviceKey);

    const now = new Date().toISOString();

    // Get all active enrollments where next_action_at has passed
    const { data: dueEnrollments, error: fetchErr } = await supabase
      .from('cadence_enrollments')
      .select('*, follow_up_cadences(name, target_type)')
      .eq('status', 'active')
      .lte('next_action_at', now);

    if (fetchErr) throw fetchErr;

    let processed = 0;
    let activitiesCreated = 0;

    for (const enrollment of (dueEnrollments || [])) {
      // Get the current step
      const { data: currentStep } = await supabase
        .from('cadence_steps')
        .select('*')
        .eq('cadence_id', enrollment.cadence_id)
        .eq('step_order', enrollment.current_step)
        .single();

      if (!currentStep) {
        // No more steps - mark completed
        await supabase.from('cadence_enrollments').update({
          status: 'completed',
          completed_at: now,
        }).eq('id', enrollment.id);
        processed++;
        continue;
      }

      // Create the activity
      const activityData: any = {
        type: currentStep.action_type,
        subject: currentStep.subject,
        description: currentStep.description || `Auto-generated by cadence: ${enrollment.follow_up_cadences?.name}`,
        priority: currentStep.priority || 'medium',
        status: 'pending',
        due_date: now,
      };

      if (enrollment.lead_id) {
        activityData.business_partner_id = enrollment.lead_id;
      }
      if (enrollment.opportunity_id) {
        activityData.opportunity_id = enrollment.opportunity_id;
      }

      const { data: activity, error: actErr } = await supabase
        .from('activities')
        .insert(activityData)
        .select()
        .single();

      if (actErr) {
        console.error('Failed to create activity:', actErr);
        continue;
      }

      activitiesCreated++;

      // Log execution
      await supabase.from('cadence_execution_log').insert({
        enrollment_id: enrollment.id,
        step_id: currentStep.id,
        activity_id: activity?.id || null,
        status: 'completed',
      });

      // Check if there's a next step
      const { data: nextStep } = await supabase
        .from('cadence_steps')
        .select('*')
        .eq('cadence_id', enrollment.cadence_id)
        .eq('step_order', enrollment.current_step + 1)
        .single();

      if (nextStep) {
        // Advance to next step
        const nextActionAt = new Date(Date.now() + nextStep.delay_days * 24 * 60 * 60 * 1000).toISOString();
        await supabase.from('cadence_enrollments').update({
          current_step: enrollment.current_step + 1,
          next_action_at: nextActionAt,
        }).eq('id', enrollment.id);
      } else {
        // No more steps - completed
        await supabase.from('cadence_enrollments').update({
          status: 'completed',
          completed_at: now,
        }).eq('id', enrollment.id);
      }

      processed++;
    }

    return new Response(
      JSON.stringify({ success: true, processed, activitiesCreated }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    console.error('Cadence processing error:', error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
