import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { useCountryPacks, useGlobalComplianceMutations, useLegalEntityCompliance } from '@/hooks/useGlobalCompliance';
import { Building2, Plus } from 'lucide-react';

export default function LegalEntityCompliance() {
  const { data: entities } = useLegalEntityCompliance();
  const { data: packs } = useCountryPacks();
  const { upsertEntity } = useGlobalComplianceMutations();
  const [form, setForm] = useState({ legal_entity_name: '', country_code: 'GLOBAL', country_pack_id: '', activation_mode: 'legal_entity_override', active_modules: 'tax,invoicing,e_documents,statutory_reports', primary_language: 'en', fiscal_calendar_code: 'GENERIC' });
  return <div className="p-4 md:p-6 space-y-6"><div className="flex justify-between items-center"><div><h1 className="text-2xl font-bold flex items-center gap-2"><Building2 className="h-6 w-6 text-primary" /> Legal Entity Enablement</h1><p className="text-sm text-muted-foreground">Hybrid country-pack rollout with legal-entity overrides</p></div><Dialog><DialogTrigger asChild><Button><Plus className="h-4 w-4 mr-2" /> Activate Entity</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Activate Compliance</DialogTitle></DialogHeader><div className="space-y-3"><div><Label>Legal Entity</Label><Input value={form.legal_entity_name} onChange={(e) => setForm({ ...form, legal_entity_name: e.target.value })} /></div><div><Label>Country Pack</Label><Select value={form.country_pack_id} onValueChange={(v) => setForm({ ...form, country_pack_id: v, country_code: (packs || []).find((p: any) => p.id === v)?.country_code || 'GLOBAL' })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{(packs || []).map((p: any) => <SelectItem key={p.id} value={p.id}>{p.pack_name}</SelectItem>)}</SelectContent></Select></div><div><Label>Active Modules</Label><Input value={form.active_modules} onChange={(e) => setForm({ ...form, active_modules: e.target.value })} /></div><div className="grid grid-cols-2 gap-2"><div><Label>Language</Label><Input value={form.primary_language} onChange={(e) => setForm({ ...form, primary_language: e.target.value })} /></div><div><Label>Calendar</Label><Input value={form.fiscal_calendar_code} onChange={(e) => setForm({ ...form, fiscal_calendar_code: e.target.value })} /></div></div><Button className="w-full" onClick={() => upsertEntity.mutate({ ...form, active_modules: form.active_modules.split(',').map((x) => x.trim()).filter(Boolean), go_live_date: new Date().toISOString().slice(0,10) })}>Activate</Button></div></DialogContent></Dialog></div><div className="grid md:grid-cols-2 gap-4">{(entities || []).map((e: any) => <Card key={e.id}><CardHeader className="pb-2"><CardTitle className="text-sm">{e.legal_entity_name}</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex gap-2"><Badge>{e.country_code}</Badge><Badge variant={e.status === 'active' ? 'default' : 'secondary'}>{e.status}</Badge><Badge variant="outline">{e.activation_mode}</Badge></div><p className="text-xs text-muted-foreground">Pack: {e.global_country_packs?.pack_name || 'Not assigned'}</p><div className="flex flex-wrap gap-1">{(e.active_modules || []).map((m: string) => <Badge key={m} variant="secondary">{m}</Badge>)}</div></CardContent></Card>)}{!entities?.length && <Card className="md:col-span-2"><CardContent className="p-10 text-center text-sm text-muted-foreground">No legal entities activated</CardContent></Card>}</div></div>;
}
