
ALTER TABLE public.cpms_daily_reports
  ADD COLUMN IF NOT EXISTS humidity INTEGER,
  ADD COLUMN IF NOT EXISTS wind_speed NUMERIC,
  ADD COLUMN IF NOT EXISTS rain_mm NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS shift TEXT DEFAULT 'day',
  ADD COLUMN IF NOT EXISTS subcontractor_summary TEXT,
  ADD COLUMN IF NOT EXISTS material_receipts TEXT,
  ADD COLUMN IF NOT EXISTS inspections_conducted TEXT,
  ADD COLUMN IF NOT EXISTS next_day_plan TEXT,
  ADD COLUMN IF NOT EXISTS gps_lat NUMERIC,
  ADD COLUMN IF NOT EXISTS gps_lng NUMERIC,
  ADD COLUMN IF NOT EXISTS submitted_offline BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS photo_urls TEXT[];
