INSERT INTO page_help_content (page_key, page_route, title_en, title_ar, description_en, description_ar, bullets_en, bullets_ar, is_active, auto_popup_enabled)
VALUES
-- POS Module
('pos_dashboard', '/pos', 'POS Dashboard', 'لوحة نقاط البيع', 'Overview of Point of Sale performance and KPIs', 'نظرة عامة على أداء نقاط البيع ومؤشرات الأداء', '{"View daily sales summary","Monitor cashier performance","Track payment method mix","Analyze branch POS activity"}', '{"عرض ملخص المبيعات اليومية","مراقبة أداء الكاشير","تتبع مزيج طرق الدفع","تحليل نشاط نقاط البيع بالفرع"}', true, true),
('pos_terminal', '/pos/terminal', 'POS Terminal', 'شاشة البيع', 'Fast cashier sales screen for checkout operations', 'شاشة البيع السريعة لعمليات الدفع', '{"Scan or search items by barcode/SKU","Add items to cart with quantity and discount","Process multi-payment checkout","Hold and resume sales transactions"}', '{"مسح أو بحث الأصناف بالباركود","إضافة أصناف للسلة مع الكمية والخصم","معالجة الدفع المتعدد","تعليق واستئناف المعاملات"}', true, true),
('pos_sessions', '/pos/sessions', 'POS Sessions', 'جلسات نقاط البيع', 'Manage cashier shifts and cash reconciliation', 'إدارة ورديات الكاشير وتسوية النقد', '{"Open and close cashier shifts","Record opening and closing cash","Calculate over/short variances","Generate X and Z reports"}', '{"فتح وإغلاق ورديات الكاشير","تسجيل النقد الافتتاحي والختامي","حساب فروقات الزيادة/النقص","إنشاء تقارير X و Z"}', true, true),
('pos_transactions', '/pos/transactions', 'POS Transactions', 'معاملات نقاط البيع', 'View and manage all POS sales transactions', 'عرض وإدارة جميع معاملات البيع', '{"Browse all POS invoices","Filter by date, cashier, branch","View transaction details and payments","Track transaction status"}', '{"تصفح جميع فواتير نقاط البيع","التصفية حسب التاريخ والكاشير والفرع","عرض تفاصيل المعاملة والمدفوعات","تتبع حالة المعاملة"}', true, true),
('pos_returns', '/pos/returns', 'POS Returns & Exchanges', 'مرتجعات واستبدالات', 'Process sales returns and item exchanges', 'معالجة مرتجعات المبيعات واستبدال الأصناف', '{"Create return against original invoice","Process full or partial returns","Handle item exchanges","Track refund approvals and reasons"}', '{"إنشاء مرتجع مقابل الفاتورة الأصلية","معالجة المرتجعات الكاملة أو الجزئية","التعامل مع استبدال الأصناف","تتبع موافقات وأسباب الاسترداد"}', true, true),
('pos_settings', '/pos/settings', 'POS Settings', 'إعدادات نقاط البيع', 'Configure POS profiles, terminals, and rules', 'تكوين ملفات نقاط البيع والأجهزة والقواعد', '{"Set up POS terminals and profiles","Configure payment methods","Define receipt templates","Set discount and return policies"}', '{"إعداد أجهزة وملفات نقاط البيع","تكوين طرق الدفع","تحديد قوالب الإيصالات","تعيين سياسات الخصم والمرتجعات"}', true, true),
('pos_quick_sale', '/pos/quick-sale', 'POS Quick Sale', 'بيع سريع', 'Streamlined quick sale interface for fast checkout', 'واجهة بيع سريعة مبسطة للدفع السريع', '{"Quick item entry by barcode","One-click payment processing","Instant receipt generation","Minimal-step checkout flow"}', '{"إدخال سريع بالباركود","معالجة دفع بنقرة واحدة","إنشاء إيصال فوري","تدفق دفع بأقل الخطوات"}', true, true),
('loyalty_wallet', '/loyalty-wallet', 'Loyalty & Wallet', 'الولاء والمحفظة', 'Manage customer loyalty programs and digital wallets', 'إدارة برامج ولاء العملاء والمحافظ الرقمية', '{"View loyalty point balances","Configure earning and redemption rules","Track customer tier progress","Manage digital wallet top-ups"}', '{"عرض أرصدة نقاط الولاء","تكوين قواعد الكسب والاستبدال","تتبع تقدم مستوى العميل","إدارة شحن المحفظة الرقمية"}', true, true),
('pos_promotions', '/pos-promotions', 'POS Promotions', 'عروض نقاط البيع', 'Create and manage POS promotional campaigns', 'إنشاء وإدارة حملات عروض نقاط البيع', '{"Create percentage or amount discounts","Set up buy-X-get-Y offers","Schedule time-based promotions","Target by branch or customer group"}', '{"إنشاء خصومات نسبية أو مبالغ","إعداد عروض اشترِ X واحصل Y","جدولة العروض الزمنية","الاستهداف حسب الفرع أو مجموعة العملاء"}', true, true),

-- Restaurant Management Module
('restaurant_dashboard', '/restaurant', 'Restaurant Dashboard', 'لوحة إدارة المطعم', 'Real-time restaurant operations overview and KPIs', 'نظرة عامة على عمليات المطعم ومؤشرات الأداء', '{"Monitor daily sales by channel","Track kitchen performance","View table occupancy rates","Analyze hourly order trends"}', '{"مراقبة المبيعات اليومية حسب القناة","تتبع أداء المطبخ","عرض معدلات إشغال الطاولات","تحليل اتجاهات الطلبات بالساعة"}', true, true),
('restaurant_menu', '/restaurant/menu', 'Menu Management', 'إدارة القائمة', 'Create and manage restaurant menu items and categories', 'إنشاء وإدارة أصناف وفئات قائمة المطعم', '{"Add menu items with variants and modifiers","Set branch-specific pricing","Schedule time-based availability","Link items to inventory recipes"}', '{"إضافة أصناف القائمة مع المتغيرات والإضافات","تعيين أسعار خاصة بالفرع","جدولة التوفر الزمني","ربط الأصناف بوصفات المخزون"}', true, true),
('restaurant_pos', '/restaurant/pos', 'Restaurant POS', 'نقطة بيع المطعم', 'Touch-friendly order taking for dine-in, takeaway, and delivery', 'أخذ الطلبات باللمس للمطعم والاستلام والتوصيل', '{"Create dine-in orders by table","Process takeaway and delivery orders","Apply modifiers and special requests","Handle multi-payment and tips"}', '{"إنشاء طلبات الجلوس حسب الطاولة","معالجة طلبات الاستلام والتوصيل","تطبيق الإضافات والطلبات الخاصة","التعامل مع الدفع المتعدد والإكراميات"}', true, true),
('restaurant_tables', '/restaurant/tables', 'Table Management', 'إدارة الطاولات', 'Visual floor map and table status management', 'خريطة الطابق المرئية وإدارة حالة الطاولات', '{"View real-time table status","Assign servers to tables","Merge and split tables","Track table turnover and occupancy"}', '{"عرض حالة الطاولات الفورية","تعيين النوادل للطاولات","دمج وفصل الطاولات","تتبع دوران وإشغال الطاولات"}', true, true),
('restaurant_kitchen', '/restaurant/kitchen', 'Kitchen Display', 'شاشة المطبخ', 'Kitchen order management and preparation tracking', 'إدارة طلبات المطبخ وتتبع التحضير', '{"View incoming kitchen tickets","Route orders to stations","Track preparation times","Handle re-fire and priority orders"}', '{"عرض تذاكر المطبخ الواردة","توجيه الطلبات للمحطات","تتبع أوقات التحضير","التعامل مع إعادة الطهي والطلبات ذات الأولوية"}', true, true),
('restaurant_shifts', '/restaurant/shifts', 'Restaurant Shifts', 'ورديات المطعم', 'Manage restaurant staff shifts and scheduling', 'إدارة ورديات وجدولة موظفي المطعم', '{"Open and close restaurant shifts","Record cash movements during shift","Perform end-of-shift reconciliation","Generate shift summary reports"}', '{"فتح وإغلاق ورديات المطعم","تسجيل حركات النقد خلال الوردية","إجراء تسوية نهاية الوردية","إنشاء تقارير ملخص الوردية"}', true, true),
('restaurant_orders', '/restaurant/orders', 'Restaurant Orders', 'طلبات المطعم', 'Browse and manage all restaurant orders', 'تصفح وإدارة جميع طلبات المطعم', '{"View orders by channel and status","Filter by date, server, or table","Track order lifecycle","Access order details and payments"}', '{"عرض الطلبات حسب القناة والحالة","التصفية حسب التاريخ أو النادل أو الطاولة","تتبع دورة حياة الطلب","الوصول لتفاصيل الطلب والمدفوعات"}', true, true),
('restaurant_reservations', '/restaurant/reservations', 'Reservations', 'الحجوزات', 'Manage table reservations and waitlist', 'إدارة حجوزات الطاولات وقائمة الانتظار', '{"Create and confirm reservations","Manage party size and special requests","Handle waitlist queue","Convert reservations to seated orders"}', '{"إنشاء وتأكيد الحجوزات","إدارة حجم المجموعة والطلبات الخاصة","إدارة قائمة الانتظار","تحويل الحجوزات إلى طلبات جالسة"}', true, true),
('restaurant_delivery', '/restaurant/delivery', 'Delivery Management', 'إدارة التوصيل', 'Manage delivery orders, riders, and dispatch', 'إدارة طلبات التوصيل والسائقين والإرسال', '{"Assign riders to delivery orders","Track delivery status in real-time","Manage zone-based delivery fees","Reconcile cash-on-delivery payments"}', '{"تعيين السائقين لطلبات التوصيل","تتبع حالة التوصيل الفوري","إدارة رسوم التوصيل حسب المنطقة","تسوية مدفوعات الدفع عند الاستلام"}', true, true),
('restaurant_settings', '/restaurant/settings', 'Restaurant Settings', 'إعدادات المطعم', 'Configure restaurant branches, areas, and operational rules', 'تكوين فروع المطعم والمناطق والقواعد التشغيلية', '{"Set up dining areas and tables","Configure kitchen stations","Define tax and service charge rules","Manage branch-level settings"}', '{"إعداد مناطق الطعام والطاولات","تكوين محطات المطبخ","تحديد قواعد الضريبة ورسوم الخدمة","إدارة إعدادات مستوى الفرع"}', true, true),
('restaurant_loyalty', '/restaurant/loyalty', 'Restaurant Loyalty', 'ولاء المطعم', 'Customer loyalty programs and promotions for restaurants', 'برامج ولاء العملاء والعروض للمطاعم', '{"Configure loyalty earning rules","Manage customer tiers and rewards","Create restaurant promotions","Track redemption and campaign performance"}', '{"تكوين قواعد كسب الولاء","إدارة مستويات ومكافآت العملاء","إنشاء عروض المطعم","تتبع الاستبدال وأداء الحملات"}', true, true),
('restaurant_recipes', '/restaurant/recipes', 'Recipe & Costing', 'الوصفات والتكلفة', 'Manage recipes, BOMs, and food cost analysis', 'إدارة الوصفات وقوائم المواد وتحليل تكلفة الغذاء', '{"Create recipes with ingredient BOMs","Calculate food cost per item","Compare standard vs actual cost","Track recipe versions and yield"}', '{"إنشاء وصفات مع قوائم المكونات","حساب تكلفة الغذاء لكل صنف","مقارنة التكلفة المعيارية والفعلية","تتبع إصدارات الوصفة والعائد"}', true, true),
('restaurant_inventory', '/restaurant/inventory', 'Restaurant Inventory', 'مخزون المطعم', 'Track ingredient stock, waste, and consumption variance', 'تتبع مخزون المكونات والهدر وفروقات الاستهلاك', '{"Monitor ingredient stock levels","Log waste and spoilage entries","Compare theoretical vs actual consumption","Trigger purchase requisitions for low stock"}', '{"مراقبة مستويات مخزون المكونات","تسجيل إدخالات الهدر والتلف","مقارنة الاستهلاك النظري والفعلي","تشغيل طلبات الشراء للمخزون المنخفض"}', true, true),
('restaurant_reports', '/restaurant/reports', 'Restaurant Reports', 'تقارير المطعم', 'Analytics dashboards and operational reports', 'لوحات التحليلات والتقارير التشغيلية', '{"View menu engineering matrix","Analyze sales by hour and channel","Track food cost percentage","Monitor kitchen and delivery performance"}', '{"عرض مصفوفة هندسة القائمة","تحليل المبيعات بالساعة والقناة","تتبع نسبة تكلفة الغذاء","مراقبة أداء المطبخ والتوصيل"}', true, true)
ON CONFLICT (page_key) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  description_en = EXCLUDED.description_en,
  description_ar = EXCLUDED.description_ar,
  bullets_en = EXCLUDED.bullets_en,
  bullets_ar = EXCLUDED.bullets_ar,
  is_active = EXCLUDED.is_active;